package org.mule.transport.legstar.transformer;
import java.io.InputStream;

import org.mule.transport.legstar.http.transformer.AbstractObjectToHttpResponse;

import com.legstar.coxb.transform.HostTransformException;

/**
 * LegStar/Mule Operation LsfileacResponseHolder to Http response Transformer.
 * 
 * <code>LsfileacResponseHolderToHttpResponse</code> takes a LsfileacResponseHolder
 * object as input, as well as a series of properties to create an http
 * response with binary content in host format (EBCDIC) ready to be sent
 * to a target Mainframe.
 * 
 * This class was generated by LegStar Mule Component generator.
 */
public class LsfileacXmlToHttpResponseTransformer
        extends AbstractObjectToHttpResponse {

    /**
     * Constructs the transformer. Source is XML.
     */
    public LsfileacXmlToHttpResponseTransformer() {
        super();
        registerSourceType(String.class);
        registerSourceType(byte[].class);
        registerSourceType(InputStream.class);
    }

    /** {@inheritDoc} */
    public IObjectToHostTransformer getObjectToHostMuleTransformer() throws HostTransformException {
        return new LsfileacXmlToHostTransformer();
    }

}
