package org.mule.transport.legstar.transformers;
import org.mule.transport.legstar.http.transformers.AbstractObjectToHttpResponseTransformer;

import com.legstar.test.coxb.lsfileae.Dfhcommarea;


/**
 * LegStar/Mule Operation Dfhcommarea to Http response Transformer.
 * 
 * <code>LsfileaeJavaToHttpResponse</code> takes a Dfhcommarea
 * object as input, as well as a series of properties to create an http
 * response with binary content in host format (EBCDIC) ready to be sent
 * to a target Mainframe.
 * 
 * This class was generated by LegStar Mule Component generator.
 */
public class LsfileaeJavaToHttpResponseTransformer
        extends AbstractObjectToHttpResponseTransformer {

    /**
     * Constructs the transformer. Source is a Dfhcommarea object.
     */
    public LsfileaeJavaToHttpResponseTransformer() {
        super();
        registerSourceType(Dfhcommarea.class);
    }

    /** {@inheritDoc} */
    public AbstractHostMuleTransformer getJavaToHostMuleTransformer() {
        return new LsfileaeJavaToHostTransformer();
    }

}
