/*******************************************************************************
 * Copyright (c) 2009 LegSem.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser Public License v2.1
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * 
 * Contributors:
 *     LegSem - initial API and implementation
 ******************************************************************************/
package org.mule.transport.legstar.test.lsfileae;
import org.mule.transformer.types.DataTypeFactory;
import org.mule.transport.legstar.transformer.AbstractHostToJavaMuleTransformer;
import com.legstar.test.coxb.lsfileae.Dfhcommarea;
import com.legstar.test.coxb.lsfileae.bind.DfhcommareaTransformers;

/**
 * Host Byte Array to Dfhcommarea Mule Transformer.
 * <p/>
 * <code>HostToDfhcommareaMuleTransformer</code> takes a byte array in host format
 * (EBCDIC) coming from a source Mainframe as input and turns it into
 * a Dfhcommarea object.
 * <p/>
 * Class generated by LegStar Mule Component generator.
 */
public class HostToDfhcommareaMuleTransformer extends AbstractHostToJavaMuleTransformer {

    /**
     * Constructs the transformer. Source is a byte array and result will be
     * a Dfhcommarea object.
     */
    public HostToDfhcommareaMuleTransformer() {
        super(new DfhcommareaTransformers());
        setReturnDataType(DataTypeFactory.create(Dfhcommarea.class));
    }


}
